name: greenlight-api-db

services:

  db:
    image: postgres
    restart: on-failure
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080

